### ISSUE TITLE
Field confirmation

### ISSUE THREAD

**Issue by TOMBowei** [fongziyjun16/SE#13]
About the communication between frontend and backend, we probably need to confirm different fields in different components such as query articles, etc.

**Comment by XIA1900** [comment]
1. Two types of users:
- Normal users (UFID, password)
- Administrators (UFID, password)

2. Personal Information
(username, gender, age, grade)

3. Post
(postId, title, content)

4. Friends list


------TBC

**Comment by XIA1900** [comment]
We have added a part in "Projects - Frontend - In progress". All parts that we want to show are listed there.
