### ISSUE TITLE
Which web backend framework should we use?

### ISSUE THREAD

**Issue by TOMBowei** [fongziyjun16/SE#5]

**Comment by fongziyjun16** [comment]
I have found beego, gin, Iris and echo, but we can try gin because it is popular, meaning when we meet some problems we find the solutions quickly.

**Comment by fongziyjun16** [comment]
For database we can use gorm to operate. For cache we can use nosql db Redis. For log we can use uber/zap. At the same time, we can extract configuration information into a yaml file and load config into system before start.
